# Generated by Django 4.2.1 on 2023-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_category_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
