# Generated by Django 4.2.1 on 2023-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_booking_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
